import time

def start_simulation():
    import webSocketClient

    # import insde function to avoid circular reference
    # First t=0
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(0)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    # 5 -> t= 0.5
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    # 5 -> t= 1
    print("SHOULD ACTIVE_1")

    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)

    print("SHOULD ACTIVE_2")

    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)

    print("SHOULD ACTIVE_3")

    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)

    print("SHOULD ACTIVE_4")

    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)

    print("SHOULD ACTIVE_5")

    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
    time.sleep(0.1)
    webSocketClient.handle_serial_data(1)
